version: '2.2'

services:
  db:
    container_name: pg_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reddit
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  reddit-backend: 
    container_name: backend
    build: ./reddit-backend
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - ./reddit-backend:/app
      - reddit-backend_node-modules:/app/node_modules
    env_file:
      - ./reddit-backend/.env

volumes: 
  postgres-data:
  reddit-backend_node-modules:
